__title__ = 'MyFab'
__description__ = 'My Fabric scripts'
__url__ = 'https://github.com/cooleasyhan/myfab'
__version__ = '0.0.1'
__author__ = 'yihan'
__author_email__ = 'yihan.cug@hotmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 yihan'